version: '3.9'
services:
  database_server:
    container_name: mysqlsrv
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=intec-123
    ports:
      - '3306:3306'
    volumes:
      - './:/home/scripts/'
